import type { Metadata } from "next";
import { Radar } from "lucide-react";

import { TrackPageEvent } from "@/components/analytics/track-page-event";
import { AtsCheckerTool } from "@/components/marketing/ats-checker-tool";
import { MarketingHeader } from "@/components/marketing/marketing-header";
import { BRAND } from "@/lib/brand";

type SearchParams = Promise<{ s?: string; m?: string; x?: string }>;

/** Shared-link score from ?s=, or null when absent/garbage. */
function sharedScore(raw: string | undefined): number | null {
  if (!raw) return null;
  const value = Number.parseInt(raw, 10);
  if (Number.isNaN(value) || value < 0 || value > 100) return null;
  return value;
}

const BASE_DESCRIPTION =
  "Paste a job description and your resume to see which of the role's keywords a recruiter would find in your resume, and which are missing. Free, no account needed.";

/**
 * Shared links (`?s=72&m=9&x=4`) unfurl as a score card: the OG image is
 * generated by /api/og/checker from the same params. Only the numbers travel
 * in the URL — never resume or job content.
 */
export async function generateMetadata({
  searchParams,
}: {
  searchParams: SearchParams;
}): Promise<Metadata> {
  const params = await searchParams;
  const score = sharedScore(params.s);

  if (score === null) {
    return {
      title: `Free ATS Resume Checker | ${BRAND.name}`,
      description: BASE_DESCRIPTION,
    };
  }

  const og = new URLSearchParams({ s: String(score) });
  if (params.m) og.set("m", params.m);
  if (params.x) og.set("x", params.x);

  return {
    title: `A ${score}/100 keyword match | ${BRAND.name}`,
    description: `Someone scored ${score}/100 matching their resume to a job. ${BASE_DESCRIPTION}`,
    openGraph: {
      images: [
        {
          url: `/api/og/checker?${og.toString()}`,
          width: 1200,
          height: 630,
        },
      ],
    },
    twitter: { card: "summary_large_image" },
  };
}

export default async function AtsCheckerPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  const score = sharedScore((await searchParams).s);

  return (
    <main className="min-h-dvh bg-background text-on-background">
      <TrackPageEvent event="checker_page_viewed" />
      <MarketingHeader />

      <div className="mx-auto max-w-6xl px-6 py-12 md:py-16">
        {score !== null ? (
          <div className="mx-auto mb-8 flex max-w-2xl items-center justify-center gap-3 rounded-lg border border-indigo-hi/30 bg-indigo-hi/10 px-4 py-3 text-sm text-on-surface">
            <Radar className="size-4 shrink-0 text-indigo-hi" />
            Someone shared a {score}/100 keyword match. Paste your own resume
            below to see where you stand.
          </div>
        ) : null}

        <div className="mx-auto mb-10 max-w-2xl text-center">
          <span className="text-xs font-medium uppercase tracking-[0.06em] text-primary">
            Free tool · no account
          </span>
          <h1 className="mt-3 font-heading text-[32px] font-bold leading-[1.15] tracking-tight text-on-surface md:text-[44px]">
            See your resume the way a recruiter searches it
          </h1>
          <p className="mt-4 text-base leading-6 text-on-surface-variant">
            Paste a job description and your resume. We&apos;ll show which of
            the role&apos;s keywords show up in your resume and which are
            missing, using the same engine that powers {BRAND.name}. Not a
            robot verdict: a relevance check you can act on.
          </p>
        </div>

        <AtsCheckerTool />

        <p className="mx-auto mt-10 max-w-2xl text-center text-xs text-on-surface-variant">
          Your resume and the job description are used only to compute this
          score and are not stored. Uploaded files are read for their text and
          discarded.
        </p>
      </div>
    </main>
  );
}
